import numpy as np
import pandas as pd

def all_suffixes(s):
    liste_suffixes = [s[i:] for i in range(0, len(s))]

    liste_entiers = list(range(1, len(s)+1))

    tableau = pd.DataFrame()
    tableau['Suffixe'] = liste_suffixes
    tableau['Entier'] = liste_entiers

    tableau = tableau.iloc[tableau.Suffixe.str.lower().argsort()]

    return tableau.Entier.as_matrix()

import time

start = time.time()
print(all_suffixes('Ler'))
end = time.time()
print(end - start)

start = time.time()
all_suffixes('Malbodge')
end = time.time()
print(end - start)

start = time.time()
all_suffixes('MalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortue')
end = time.time()
print(end - start)

start = time.time()
all_suffixes('MalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortue')
end = time.time()
print(end - start)

start = time.time()
all_suffixes('MalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortueMalbodgeChiensTortue')
end = time.time()
print(end - start)